//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfTrainingExample
{
    using System.Runtime.Serialization;
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FibonacciRequest", Namespace="http://schemas.datacontract.org/2004/07/WcfTrainingExample")]
    public partial class FibonacciRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NumberField;
        
        private bool UseRecursiveAlgorithmField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseRecursiveAlgorithm
        {
            get
            {
                return this.UseRecursiveAlgorithmField;
            }
            set
            {
                this.UseRecursiveAlgorithmField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FibonacciResult", Namespace="http://schemas.datacontract.org/2004/07/WcfTrainingExample")]
    public partial class FibonacciResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WcfTrainingExample.FibonacciValue DataField;
        
        private string ErrorsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfTrainingExample.FibonacciValue Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FibonacciValue", Namespace="http://schemas.datacontract.org/2004/07/WcfTrainingExample")]
    public partial class FibonacciValue : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FormulaField;
        
        private int IterationsField;
        
        private int ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formula
        {
            get
            {
                return this.FormulaField;
            }
            set
            {
                this.FormulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Iterations
        {
            get
            {
                return this.IterationsField;
            }
            set
            {
                this.IterationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IExampleService")]
public interface IExampleService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/TestServiceWebGet", ReplyAction="http://tempuri.org/IExampleService/TestServiceWebGetResponse")]
    string TestServiceWebGet(string data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/TestServiceWebGet", ReplyAction="http://tempuri.org/IExampleService/TestServiceWebGetResponse")]
    System.Threading.Tasks.Task<string> TestServiceWebGetAsync(string data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/TestServiceWebPost", ReplyAction="http://tempuri.org/IExampleService/TestServiceWebPostResponse")]
    string TestServiceWebPost(string data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/TestServiceWebPost", ReplyAction="http://tempuri.org/IExampleService/TestServiceWebPostResponse")]
    System.Threading.Tasks.Task<string> TestServiceWebPostAsync(string data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/TestService", ReplyAction="http://tempuri.org/IExampleService/TestServiceResponse")]
    string TestService(string data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/TestService", ReplyAction="http://tempuri.org/IExampleService/TestServiceResponse")]
    System.Threading.Tasks.Task<string> TestServiceAsync(string data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/FibonacciWebGet", ReplyAction="http://tempuri.org/IExampleService/FibonacciWebGetResponse")]
    string FibonacciWebGet(string number, string useRecursiveAlgorithm);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/FibonacciWebGet", ReplyAction="http://tempuri.org/IExampleService/FibonacciWebGetResponse")]
    System.Threading.Tasks.Task<string> FibonacciWebGetAsync(string number, string useRecursiveAlgorithm);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/FibonacciWebPost", ReplyAction="http://tempuri.org/IExampleService/FibonacciWebPostResponse")]
    string FibonacciWebPost(WcfTrainingExample.FibonacciRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/FibonacciWebPost", ReplyAction="http://tempuri.org/IExampleService/FibonacciWebPostResponse")]
    System.Threading.Tasks.Task<string> FibonacciWebPostAsync(WcfTrainingExample.FibonacciRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/Fibonacci", ReplyAction="http://tempuri.org/IExampleService/FibonacciResponse")]
    WcfTrainingExample.FibonacciResult Fibonacci(WcfTrainingExample.FibonacciRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/Fibonacci", ReplyAction="http://tempuri.org/IExampleService/FibonacciResponse")]
    System.Threading.Tasks.Task<WcfTrainingExample.FibonacciResult> FibonacciAsync(WcfTrainingExample.FibonacciRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IExampleServiceChannel : IExampleService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ExampleServiceClient : System.ServiceModel.ClientBase<IExampleService>, IExampleService
{
    
    public ExampleServiceClient()
    {
    }
    
    public ExampleServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ExampleServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ExampleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ExampleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string TestServiceWebGet(string data)
    {
        return base.Channel.TestServiceWebGet(data);
    }
    
    public System.Threading.Tasks.Task<string> TestServiceWebGetAsync(string data)
    {
        return base.Channel.TestServiceWebGetAsync(data);
    }
    
    public string TestServiceWebPost(string data)
    {
        return base.Channel.TestServiceWebPost(data);
    }
    
    public System.Threading.Tasks.Task<string> TestServiceWebPostAsync(string data)
    {
        return base.Channel.TestServiceWebPostAsync(data);
    }
    
    public string TestService(string data)
    {
        return base.Channel.TestService(data);
    }
    
    public System.Threading.Tasks.Task<string> TestServiceAsync(string data)
    {
        return base.Channel.TestServiceAsync(data);
    }
    
    public string FibonacciWebGet(string number, string useRecursiveAlgorithm)
    {
        return base.Channel.FibonacciWebGet(number, useRecursiveAlgorithm);
    }
    
    public System.Threading.Tasks.Task<string> FibonacciWebGetAsync(string number, string useRecursiveAlgorithm)
    {
        return base.Channel.FibonacciWebGetAsync(number, useRecursiveAlgorithm);
    }
    
    public string FibonacciWebPost(WcfTrainingExample.FibonacciRequest request)
    {
        return base.Channel.FibonacciWebPost(request);
    }
    
    public System.Threading.Tasks.Task<string> FibonacciWebPostAsync(WcfTrainingExample.FibonacciRequest request)
    {
        return base.Channel.FibonacciWebPostAsync(request);
    }
    
    public WcfTrainingExample.FibonacciResult Fibonacci(WcfTrainingExample.FibonacciRequest request)
    {
        return base.Channel.Fibonacci(request);
    }
    
    public System.Threading.Tasks.Task<WcfTrainingExample.FibonacciResult> FibonacciAsync(WcfTrainingExample.FibonacciRequest request)
    {
        return base.Channel.FibonacciAsync(request);
    }
}
